// 自动生成于 parse_v3.py
// 共 166 道题

export interface Question {
  id: string;
  grade: Grade;
  type: QuestionType;
  typeLabel: string;
  question: string;
  answer: string;
  explanation?: string;
  tags?: string[];
}

export const questionBank: Question[] = [
  {
    id: "g1-q-001",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题1  【声母认读】  基础\n下列声母中，哪一个发音时嘴唇要闭合？\nA. d       B. b       C. g       D. z",
    answer: "B（b）  解析：b、p、m 发音时双唇闭合，b 是双唇不送气音。",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-002",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题2  【给汉字标拼音】  基础\n给下面的汉字写出正确的拼音：\n妈（　　）  鱼（　　）  书（　　）  花（　　）  天（　　）",
    answer: "妈 mā    鱼 yú    书 shū    花 huā    天 tiān",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-003",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题3  【声调辨别】  基础\n选出声调正确的一项：妈妈的\"妈\"应该读哪个声调？\nA. má（二声）    B. mā（一声）    C. mǎ（三声）    D. mà（四声）",
    answer: "B（mā，一声）  妈妈读 māma，第一个字是一声阴平。",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-004",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题4  【看拼音写汉字】  基础\n看拼音，写出对应的汉字：\ntài yáng（　　　　）  xiǎo niǎo（　　　　）  hé liú（　　　　）  sēn lín（　　　　）",
    answer: "太阳    小鸟    河流    森林",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-005",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题5  【整体认读音节】  中等\n下列属于整体认读音节的是哪个？\nA. ba       B. zhi       C. ma       D. da",
    answer: "B（zhi）  整体认读音节共16个：zhi chi shi ri / zi ci si / yi wu yu / ye yue yuan / yin yun ying。",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-006",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题6  【音节拼读】  中等\n拼一拼，下面的音节代表哪个词？  chūn tiān\nA. 秋天    B. 春天    C. 晴天    D. 冲天",
    answer: "B（春天）  chūn=春，tiān=天，合起来是\"春天\"。",
    explanation: "题7  【多音字】  较难  ★一升二衔接",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-007",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题7  【多音字】  较难  ★一升二衔接\n\"长\"字有几个读音？请分别组词：\ncháng：（　　　　　　　　　）\nzhǎng：（　　　　　　　　　）",
    answer: "cháng：长江、长短、长跑；  zhǎng：长大、成长、家长",
    explanation: "题8  【韵母归类】  较难  ★一升二衔接",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-008",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题8  【韵母归类】  较难  ★一升二衔接\n将下列音节按韵母分类，填入表格（单韵母/复韵母/鼻韵母）：\nān  ái  ō  iū  ǐ  uāng\n单韵母（6个）：（　　　　）    复韵母：（　　　　）    鼻韵母：（　　　　）",
    answer: "单韵母：ō、ǐ  |  复韵母：ái、iū  |  鼻韵母：ān、uāng",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-009",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题1  【笔画数】  基础\n\"日\"字共有几画？\nA. 3画    B. 4画    C. 5画    D. 6画",
    answer: "B（4画）  日：竖、横折、横、横，共4笔。",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-010",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题2  【笔顺排列】  基础\n\"王\"字的笔顺正确的是哪一项？\nA. 横、横、竖、横\nB. 横、竖、横、横\nC. 竖、横、横、横\nD. 横、横、横、竖",
    answer: "A（横、横、竖、横）  \"王\"：先上横，再中横，再竖，最后长横。",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-011",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题3  【偏旁部首】  基础\n\"妈、妹、姐\"三个字共同的偏旁是什么？这个偏旁和什么有关？\n偏旁是：（　　　　）    与（　　　　）有关",
    answer: "偏旁是\"女字旁\"（女），与女性/女人有关。",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-012",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题4  【找错别字】  中等\n下列词语中有错别字的一项是：\nA. 小鸟    B. 大树    C. 月亮    D. 太扬",
    answer: "D  \"太扬\"应为\"太阳\"，\"扬\"和\"阳\"形近，注意区分。",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-013",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题5  【按偏旁归类】  中等\n把下列汉字按偏旁分类：  河  湖  海  江  泡\n三点水的字：（　　　　　　　　　　　　　　）",
    answer: "全部（河、湖、海、江、泡）都是三点水（氵）旁，都与水有关。",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-014",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题6  【照样子写字】  中等\n照样子，在格子里写出下列汉字（注意笔顺）：\n例：大→大（书写格练习）\n人（　　）（　　）    山（　　）（　　）    水（　　）（　　）\n（请在方格纸上练习书写）",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-015",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题8  【加偏旁组新字】  较难  ★一升二衔接\n给\"青\"字加上不同的偏旁，组成新字并组词：\n青 + 氵→（　　）→ 组词：（　　　　　　）\n青 + 讠→（　　）→ 组词：（　　　　　　）\n青 + 目→（　　）→ 组词：（　　　　　　）",
    answer: "青+氵→清（清水/清楚）；青+讠→请（请问/请客）；青+目→睛（眼睛）",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-016",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题1  【反义词】  基础\n写出下列词语的反义词：\n大 →（　　）    上 →（　　）    快 →（　　）    黑 →（　　）",
    answer: "大→小    上→下    快→慢    黑→白",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-017",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题2  【词语搭配】  基础\n连一连，找到正确的词语搭配：\n美丽的——　　　　清澈的——　　　　勤劳的——　　　　金黄色的——\n（花朵 / 河水 / 蜜蜂 / 稻田）",
    answer: "美丽的花朵    清澈的河水    勤劳的蜜蜂    金黄色的稻田",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-018",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题3  【AABB式词语】  中等\n照样子，写出 AABB 式的词语。  例：高高兴兴\n（　　　　）（　　　　）（　　　　）（　　　　）",
    answer: "快快乐乐、开开心心、整整齐齐、认认真真、漂漂亮亮（合理即可）",
    explanation: "题4  【近义词】  中等  ★一升二衔接",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-019",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题4  【近义词】  中等  ★一升二衔接\n写出下列词语的近义词：\n开心 ≈（　　　）    漂亮 ≈（　　　）    喜欢 ≈（　　　）",
    answer: "开心≈快乐/高兴    漂亮≈美丽/好看    喜欢≈喜爱/热爱（合理即可）",
    explanation: "题5  【量词填空】  较难  ★一升二衔接",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-020",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题5  【量词填空】  较难  ★一升二衔接\n选择正确的量词填空（一朵/一条/一棵/一只/一片）：\n（　　）花    （　　）鱼    （　　）树    （　　）小鸟    （　　）叶子",
    answer: "一朵花    一条鱼    一棵树    一只小鸟    一片叶子",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-021",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题1  【补全句子】  基础\n补全下面的句子，使它变完整：\n小狗在（　　　　　　　　　　　　　　　　）。\n（　　　　　　　　　　　　　　　　）是我的好朋友。\n今天天气（　　　　　　　　　　　　　　　　）。",
    answer: "示例：小狗在（院子里玩耍）。（小明）是我的好朋友。今天天气（真好）。（合理即可）",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-022",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题2  【扩句练习】  中等\n给下面的句子加上修饰语，使句子更生动：\n例：小鸟飞翔。→ 可爱的小鸟在蓝天上自由地飞翔。\n蝴蝶飞舞。→（　　　　　　　　　　　　　　　　　　　　　　　　　　　　）\n小鱼游水。→（　　　　　　　　　　　　　　　　　　　　　　　　　　　　）",
    answer: "美丽的蝴蝶在花丛中翩翩起舞。活泼的小鱼在清澈的水中快乐地游来游去。（合理即可）",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-023",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题3  【感叹句改写】  中等\n把下面的句子改成感叹句（加上\"真……啊！\"等）：\n例：今天天气很好。→ 今天天气真好啊！\n这朵花很漂亮。→（　　　　　　　　　　　　　　　　　　　　　　）\n弟弟跑得很快。→（　　　　　　　　　　　　　　　　　　　　　　）",
    answer: "这朵花真漂亮啊！    弟弟跑得真快啊！（合理即可）",
    explanation: "题4  【连词成句】  较难  ★一升二衔接",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-024",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题4  【连词成句】  较难  ★一升二衔接\n把下列词语排列成正确的句子，加上标点：\n① 喜欢  小猫  玩球  非常\n→（　　　　　　　　　　　　　　　　　　　　　　）\n② 公园里  美丽的  盛开着  鲜花\n→（　　　　　　　　　　　　　　　　　　　　　　）",
    answer: "①小猫非常喜欢玩球。    ②公园里盛开着美丽的鲜花。",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-025",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题1  【短文阅读】  中等\n阅读短文，回答问题：\n【春天来了】\n春天来了，天气变得暖和了。小草从地里钻出来，绿绿的，软软的。树上长出了嫩嫩的新叶。花儿开放了，红的、黄的、白的，五颜六色，漂亮极了。小燕子从南方飞回来了，在天空中快乐地飞翔。小朋友们也脱下了厚厚的棉衣，在草地上追跑玩耍。\n（1）短文共有（　　）句话。\n（2）春天来了，天气变得（　　　　　　）了。\n（3）花儿有哪些颜色？请用\"——\"画出来。\n（4）小燕子从哪里飞回来了？（　　　　　　　　　　）",
    answer: "（1）6句话    （2）暖和    （3）红的、黄的、白的    （4）从南方飞回来",
    explanation: "题2  【理解短文】  较难  ★一升二衔接",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-026",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题2  【理解短文】  较难  ★一升二衔接\n阅读短文，回答问题：\n【小蚕】\n小蚕刚出生的时候，黑黑的，细细的，像蚂蚁一样小。它每天吃桑叶，不停地吃，不停地长大。过了一段时间，小蚕变成白色了，胖乎乎的，软软的。它会吐丝，把自己包裹起来，做成一个茧。最后，它从茧里出来，变成了一只蝴蝶一样美丽的蚕蛾。\n（1）小蚕刚出生是什么颜色？（　　　　　　　　　　）\n（2）小蚕长大了变成什么颜色？（　　　　　　　　　　）\n（3）小蚕最后变成了什么？（　　　　　　　　　　）\n（4）小蚕每天吃什么？（　　　　　　　　　　）",
    answer: "（1）黑色    （2）白色    （3）蚕蛾（像蝴蝶一样美丽）    （4）桑叶",
    tags: ["阅读理解"],
  },
  {
    id: "g1-q-027",
    grade: 1,
    type: "reading",
    typeLabel: "阅读理解",
    question: "题1  【看图写话】  中等  ★一升二衔接\n看图，用几句话说一说图片中发生了什么事。\n🌳 👦 🌂 ☔\n【图片内容提示】一个小朋友，大树下，正在下雨，撑着雨伞\n✏️ 写话提示：\n① 图片里有谁？在哪里？\n② 天气怎么样？（看图中的雨）\n③ 小朋友在做什么？\n④ 你觉得他心情怎么样？（可以加入想象）\n⑤ 写出 2-4 句完整的话，用上\"因为……所以……\"或\"虽然……但是……\"（一升二衔接）\n我的写话：\n＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿\n＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿\n＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿\n＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿\n＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿\n＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿",
    answer: "下雨了，天空中下起了大雨。一个小朋友站在大树下，撑着一把红色的雨伞。虽然外面下着雨，但是他一点也不害怕，因为他有雨伞保护。他开心地看着雨水打在树叶上，发出哗哗的声音。\n（评分参考：句子完整✓，内容合理✓，用上关联词加分✓）",
    tags: ["阅读理解"],
  },
  {
    id: "g2-q-001",
    grade: 2,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1.A 2.B 3.C 4.B 5.B\n阅读 2 \n\n下雨啦\n轰隆隆，轰隆隆，打雷了。\n小雨点落下来，落在树叶上，沙沙沙；落在池塘里，叮咚叮咚。\n小青蛙跳出水面，开心地唱歌；小鱼游到水面，吐出一串串泡泡。雨后空气凉凉的，天上还会出现美丽的彩虹。\n阅读习题\n短文有（）个自然段\nA.2 B.3 C.4\n文中没有写到的声音是（）\nA. 轰隆隆 B. 沙沙沙 C. 哗啦啦\n下雨时谁在唱歌？（）\nA. 小鱼 B. 小青蛙 C. 小鸟\n彩虹出现在什么时候？（）\nA. 下雨前 B. 下雨中 C. 下雨后\n下雨时小鱼会（）\nA. 躲进泥土 B. 游到水面吐泡泡 C. 躲在荷叶下",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g2-q-002",
    grade: 2,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1.A 2.B 3.B 4.B 5.B\n阅读 4 \n\n春天的花园\n春天来了，花园里真热闹。粉红的桃花、雪白的梨花全开了。\n小蜜蜂飞来采花蜜，蝴蝶穿着花裙子跳舞。小草从土里钻出来，给大地铺上绿毯子。\n小朋友们来到花园，不摘花、不踩草，安静欣赏美丽的景色。\n阅读习题\n文中没有写到的花是（）\nA. 桃花 B. 杏花 C. 梨花\n谁在花园采蜜？（）\nA. 蝴蝶 B. 蜜蜂 C. 蜻蜓\n文中把小草比作（）\nA. 绿毯子 B. 小树苗 C. 绿丝带\n小朋友到花园不会做的事（）\nA. 赏花 B. 摘花朵 C. 轻轻走路\n这篇短文写的季节是（）\nA. 春天 B. 夏天 C. 秋天",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g2-q-003",
    grade: 2,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1.B 2.C 3.B 4.B 5.C\n阅读 6 \n\n月亮\n夜晚，月亮挂在天上。有时候圆圆的，像大圆盘；有时候弯弯的，像小船。\n月亮自己不会发光，它的光是太阳送给它的。夜晚走夜路，月亮会给我们照亮小路。\n阅读习题\n圆圆的月亮像（）\nA. 小船 B. 圆盘 C. 镰刀\n弯弯的月亮像（）\nA. 小船 B. 镜子 C. 皮球\n月亮的光来自（）\nA. 自己 B. 星星 C. 太阳\n月亮可以（）\nA. 发热 B. 照亮小路 C. 下雨\n这篇短文描写的景物出现在（）\nA. 白天 B. 夜晚 C. 清晨",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g2-q-004",
    grade: 2,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1.B 2.B 3.B 4.B 5.B",
    answer: "6.A 7.A 8.B 9.B 10.B",
    tags: ["阅读理解"],
  },
  {
    id: "g2-q-005",
    grade: 2,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1.B 2.B 3.A 4.B 5.B",
    answer: "6.C 7.A 8.B 9.B 10.A",
    tags: ["阅读理解"],
  },
  {
    id: "g2-q-006",
    grade: 2,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1.C 2.A 3.A 4.B 5.A",
    answer: "6.B 7.B 8.B 9.B 10.A",
    tags: ["阅读理解"],
  },
  {
    id: "g3-q-001",
    grade: 3,
    type: "reading",
    typeLabel: "阅读理解",
    question: "5.《惠崇春江晚景》的作者是？\nA. 唐代杜甫 B. 宋代苏轼 C. 宋代王安石",
    answer: "B",
    tags: ["阅读理解"],
  },
  {
    id: "g3-q-002",
    grade: 3,
    type: "reading",
    typeLabel: "阅读理解",
    question: "6.《三衢道中》是___朝诗人___的作品。\nA. 唐；李白 B. 宋；曾几 C. 宋；杨万里",
    answer: "B",
    tags: ["阅读理解"],
  },
  {
    id: "g3-q-003",
    grade: 3,
    type: "reading",
    typeLabel: "阅读理解",
    question: "7. “春眠不觉晓，处处闻啼鸟” 的作者是唐代___？\nA. 孟浩然 B. 贺知章 C. 王之涣",
    answer: "A",
    tags: ["阅读理解"],
  },
  {
    id: "g3-q-004",
    grade: 3,
    type: "reading",
    typeLabel: "阅读理解",
    question: "8. “竹外桃花三两枝，春江水暖鸭先知”，诗句想要表达什么？\nA. 鸭子怕冷，不敢下水\nB. 早春回暖，鸭子最先感知江水温度，描绘初春美景",
    answer: "B",
    tags: ["阅读理解"],
  },
  {
    id: "g3-q-005",
    grade: 3,
    type: "reading",
    typeLabel: "阅读理解",
    question: "9._______，春风花草香。（选正确上句）\nA. 春眠不觉晓\nB. 迟日江山丽\nC. 空山新雨后",
    answer: "B",
    tags: ["阅读理解"],
  },
  {
    id: "g3-q-006",
    grade: 3,
    type: "reading",
    typeLabel: "阅读理解",
    question: "10.梅子黄时日日晴，________。\nA. 小溪泛尽却山行\nB. 添得黄鹂四五声\nC. 绿阴不减来时路",
    answer: "A",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-001",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1. 下面加点字读音，完全正确的是( )。\nA.捣乱(dǎo)    臀部(tún)      乒乓(pīn)     胸膛(táng)\nB.挣扎(zhá)    率领(shuài)    琥珀(bó)      澎湃(pài)\nC.看门(kān)    春晖(huī)      吭声(kēng)    倔强(qiáng)\nD.海啸(xiào)   派遣(qiǎn)     遗憾(hàn)     慷慨(kǎi)",
    answer: "【详解】A.乒乓(pīng)；B.琥珀(pò)；C.倔强(jiàng)。",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-002",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "2.下面加点字的读音有错误的一项是( )。\nA.嘱咐(zhǔ)     嘹亮(liáo)    睫毛(jié)    隧道(suì)\nB.渗透(shèn)    机械(xiè)    徜徉(yáng)    单于(chán)\nC.砚台(yàn)     凌晨(líng)    冰雹(báo)    遭殃(yāng)\nD.胆怯(qiè)     哺育(pǔ)      遗憾(hàn)    嚣张(xiāo)",
    answer: "【详解】本题考查字音辨析。D.哺育(pǔ)——bǔ；",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-003",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "3. 下列各项中，读音全部正确的一项是 ( ) 。\nA.镶嵌(xiāngqiàn)     蜿蜒(wānyán)      黝黑(yóuhēi)\nB.枪栓(qiāngshuān)    倔强(juè jiàng)    遗憾(yí hàn)\nC.匍匐(pú fú)         湍急(tuān jí)      亲昵(qīnnì)\nD.耽误(dānwù)         欺侮(qī rǔ)        徜徉(chángyáng)",
    answer: "【详解】本题考查字音辨析。",
    explanation: "A.黝黑(yóuhēi )——yǒu hēi；B.倔强(juèjiàng)——jué jiàng； D.耽误(dānwù)——dānwu",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-004",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "4. 下列易错字摘抄笔记中，整理得完全正确的一份是( )。\nA.辰辰：蝙蝠 霸气 响午 拥挤      B.华华：窟窿 蔬菜 胳膊 推侧\nC.原原：刹那 潇洒 隐形 观赏      D.多多：爆炸 秩序 丰硕 折除",
    answer: "【详解】A.晌午 B.推测 D.拆除",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-005",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "5. 下列选项中，词语的书写有误的一组是( )。\nA.甜蜜 警戒 敏捷 需要          B.侍候 慌忙 即将 艰巨\nC.爆炸 胳膊 疾病 详细          D.持继 聚集 拆除 综迹",
    answer: "【详解】本题考查字形易错字。 D. 持继——持续，综迹——踪迹",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-006",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "6. 下面几组词语中，没有错别字的一组是( )。\nA.辽阔无银     攸然自得     此起彼落     极目远眺\nB.草木皆兵     全神惯注     一丝不苟     胆大妄为\nC.声东击西     千里冰封     响彻云霄     穿流不息\nD.莫名其妙     鱼贯而出     挥汗如雨     赏心悦目",
    answer: "【详解】本题考查辨析错别字。",
    explanation: "A.辽阔无银——辽阔无垠，攸然自得——悠然自得；",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-007",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "7. 下面这些广告牌，书写全部正确的一项是( ) 。\nA.生态果蔬店     土灶钝乳鸽      B.防瀑轮胎    户外账篷出租\nC.丝绸刺锈定制   纳米护膝袜      D.隐形眼镜    衣服个性手绘",
    answer: "【详解】本题考查字形易错字。",
    explanation: "A.土灶钝乳鸽——土灶炖乳鸽； B.防瀑轮胎——防爆轮胎，户外账篷出租——户外帐篷出租； C.丝绸刺锈定制——丝绸刺绣定制。",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-008",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "8. 下列句子中带点的同音形近字运用错误的一项是 ( )。\nA.建设工人给正在施工的操场拉起了警戒线，告诫大家：危险勿进！\nB.我在落日的余晖中和爷爷奶奶依依不舍地挥手道别。\nC.他拉开蚊账，拿出一叠帐本轻轻地递给了儿子。\nD.阅读书籍可以让烦躁不安的心灵得到慰藉。",
    answer: "【详解】本题考查字形易错字。 C.蚊账——蚊帐，帐本——账本。",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-009",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "9. 下列加点词语中，书写正确的一项是( )。\nA.月色朦眬，披上银纱的忠山公园寂静而神秘。\nB.我们要多吃蔬菜，少喝碳酸饮料，建康成长。\nC.忠山睡道成功打通，泸州城南到城中心就变得非常便捷。\nD.雪后的泸州植物园，树枝上挂满毛茸茸的银条，一时竟分辨不出原本的样子。",
    answer: "【详解】本题考查错别字辨析。",
    explanation: "A.朦眬——朦胧； B.建康——健康； C.睡道——隧道",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-010",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "10.下列加点字的读音以及与作者对应的内容完全正确的一项是( )。\nA.韩愈(yù)——人非生而知之者，孰能无惑？\nB.范仲淹(zhòng)——春眠不觉晓，处处闻啼鸟。\nC.杜甫(pǔ)——桃花一簇开无主，可爱深红爱浅红？\nD.刘禹锡(xī)——不识庐山真面目，只缘身在此山中。",
    answer: "【详解】本题考查字音及作家作品。",
    explanation: "B.孟浩然——春眠不觉晓，处处闻啼鸟。C.杜甫．(pǔ)——fǔ； D.苏轼——不识庐山真面目，只缘身在此山中。",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-011",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "5. 下列句子运用的修辞手法与其他三项不同的一项是( ) 。\nA.三月的桃花水，是春天的明镜。\nB.两双鞋，既像四只鸟窝，又像两对鸟。\nC.小猫要是高兴，能比谁都温柔可亲。",
    answer: "【详解】A.该句把“三月的桃花水”比作“春天的明镜”，写出了水面清澈明亮 的特点。运用了比喻的修辞手法。",
    explanation: "B.该句把“两双鞋”比作“四只鸟窝”和“两对鸟”，写出了鞋子小巧、温暖可爱的特点。运 用了比喻的修辞手法。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-012",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "6.下列句子中，没有语病的一项是( ) 。\nA.在如何提高课堂效率的问题上，我校老师听取了广泛同学们的意见。\nB.这份有创意的“六一庆祝活动”策划书，出自一位四年级学生之手。\nC.在学习过程中，我们应该培养自己解决、分析、观察问题的能力。\nD.“六一”儿童节节目精彩纷呈，有唱歌、舞蹈和文娱节目。",
    answer: "【详解】本题考查病句。",
    explanation: "A.语序混乱。广泛”修饰“听取”时，位置不当。应改为“广泛听取了同学们的意见”。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-013",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "7. 下列句子中，没有运用比喻的修辞手法的一项是( )。\nA.食堂开饭时，全校的学生像热锅上的蚂蚁一样挤成一团。\nB.静静地听着音乐，他好像面对着波涛汹涌的大海。\nC.一轮镜子似的明月挂在湛蓝的天空中，为我照亮前进的路。\nD.果园里的果实成熟了，柿子笑红了脸，仿佛一个个小红灯笼挂在枝头。",
    answer: "【详解】本题考查修辞手法。 比喻就是抓住两种不同性质的事物的相似点，用一事物喻另一事物。",
    explanation: "B.“他好像面对着波涛汹涌的大海”，这里的“好像”表示一种想象的状态，没有将“他” 或者其他事物比作“大海”，没有本体和喻体，不构成比喻的修辞手法。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-014",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "8. 下面的句子中，表达的感情与其他句子不一致的是 (  ) 。\nA.它到院子里来了。院中的花草可遭了殃。它在花盆里摔跤，抱着花枝打秋千，所过 之处，枝折花落。\nB.鹅便昂首大叫，似乎责备人们供养不周。这时我们便替他添饭，并且站着待候。\nC.扁鼻子军官的眼光变得凶恶可怕，他向前弓着身子，伸出两只大手。 D.最喜小儿亡赖，溪头卧剥莲蓬。",
    answer: "【详解】本题考查句子理解及感情色彩辨析。",
    explanation: "A.这句话描述了一只小动物(可能是小猫或小狗)来到院子里，行为顽皮，导致花草受损。 虽然表面上看起来是在描述花草遭殃，但整体语气中透露出一种对小动物顽皮行为的 宽容和喜爱。这是一种带有幽默和宠溺的感情色彩。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-015",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "9. 将“但后来长期滥垦、过度放牧使它逐渐沙化”这 句话插入下面语段中，位置最恰当的一项是(  ) 。\n①在毛乌素沙漠中，有一座古城的废墟。②它曾是声威显赫的大厦国都城，规模宏大，风 景宜人。③到了宋代，古城已陷在沙漠中，人民很难生存，最终被统治者下令废毁。④这座 古城的废墟是生态学上的有力例证。⑤它仿佛在向我们诉说，要过有节制、有远见的生活。 A.①②之间    B.②③之间     C.③④之间    D.④⑤之间",
    answer: "【详解】本题考查语句衔接。 先梳理原语段各句的核心内容",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-016",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "10. 给下列句子所加的标点，最恰当的一项是( )。\n白鹅需要三样东西下饭   一样是水    一样是泥    一样是草\nA.，，，。       B.：，，。       C.：、、……       D.。，，。",
    answer: "【详解】本题考查标点符号。",
    explanation: "“白鹅需要三样东西下饭”这句话引出了后面要具体说明的内容，用冒号能起到提示下 文的作用；“一样是水”“一样是泥”“一样是草”是并列的列举项，它们之间用逗号分隔符 合表达习惯，清晰地列出了白鹅下饭的三样东西，最后用句号表示整个句子陈述结束。 故为：白鹅需要三样东西下饭：一样是水，一样是泥，一样是草。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-017",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "1. 下列哪句是王安石《泊船瓜洲》中的名句？（）。\nA. 春风送暖入屠苏 B. 春风不度玉门关 C. 春江水暖鸭先知\nD. 春潮带雨晚来急 E. 春风又绿江南岸 F. 春来江水绿如蓝",
    answer: "E",
    explanation: "：A 出自王安石《元日》；B 出自王之涣《凉州词》；C 出自苏轼《惠崇春江晚景》；D 出自韦应物《滁州西涧》；F 出自白居易《忆江南》。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-018",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "2. 李绅《悯农》“四海无闲田，农夫犹饿死” 揭露的是（）\nA. 遇到大灾害 B. 干活不努力 C. 制度不合理 D. 有志难报国",
    answer: "C",
    explanation: "：天下土地都耕种了，农民依旧挨饿，反映古代赋税繁重、剥削严重的不合理社会制度。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-019",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "3. 范成大《四时田园杂兴（其二十五）》描写的季节是（）\nA. 早春 B. 初夏 C. 深秋 D. 寒冬",
    answer: "B",
    explanation: "：诗中 “梅子金黄、杏子肥、麦花雪白” 都是初夏典型景物。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-020",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "4. “最喜小儿亡赖，溪头卧剥莲蓬” 中 “亡赖” 的意思是（）\nA. 无赖、坏人 B. 顽皮可爱 C. 没有依靠 D. 懒惰贪玩",
    answer: "B",
    explanation: "：出自辛弃疾《清平乐・村居》，这里是褒义词，形容小儿子天真淘气。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-021",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "5. 《芙蓉楼送辛渐》中 “一片冰心在玉壶” 用来比喻诗人（）\nA. 内心寒冷孤寂 B. 品格纯洁高洁 C. 喜爱玉石器皿 D. 路途艰难寒冷",
    answer: "B",
    explanation: "：冰心、玉壶象征纯净清白，表达王昌龄坚守高洁操守的志向。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-022",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "6. “不要人夸好颜色，只留清气满乾坤” 出自哪首诗？（）\nA.《蜂》 B.《墨梅》 C.《塞下曲》 D.《江畔独步寻花》",
    answer: "B",
    explanation: "：元代王冕《墨梅》，托物言志，借梅花写自身淡泊名利的品格。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-023",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "7. 毛泽东《卜算子・咏梅》中 “卜算子” 是（）\nA. 诗题 B. 词牌名 C. 地名 D. 人名",
    answer: "B",
    explanation: "：词牌规定词的格式曲调，“咏梅” 才是这首词的题目。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-024",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "8. “不论平地与山尖，无限风光尽被占” 赞美蜜蜂，暗含批判（）\nA. 山中风景太少 B. 采花太过辛苦 C. 不劳而获之人 D. 花朵容易凋零",
    answer: "C",
    explanation: "：罗隐《蜂》，蜜蜂辛劳采蜜，成果却被别人占有，讽刺剥削者。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-025",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "9. “寒雨连江夜入吴，平明送客楚山孤” 属于什么题材诗歌？（）\nA. 田园诗 B. 边塞诗 C. 送别诗 D. 咏物诗",
    answer: "C",
    explanation: "：王昌龄送别好友辛渐前往洛阳，借孤山烘托离别孤单的心情。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-026",
    grade: 4,
    type: "sentence",
    typeLabel: "句子练习",
    question: "10. “待到山花烂漫时，她在丛中笑” 运用的修辞手法是（）\nA. 比喻 B. 拟人 C. 夸张 D. 对偶",
    answer: "B",
    explanation: "：把梅花当作人来写，写出梅花谦逊无私、不争春光的品格。",
    tags: ["句子练习"],
  },
  {
    id: "g4-q-027",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1. 《鲁滨逊漂流记》作者是（）\nA. 马克・吐温 B. 丹尼尔・笛福 C. 塞尔玛・拉格洛夫 D. 卡罗尔",
    answer: "B",
    explanation: "：丹尼尔・笛福（英国）；A 是《汤姆・索亚历险记》作者；C《骑鹅旅行记》；D《爱丽丝漫游奇境》。",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-028",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "2. 鲁滨逊流落荒岛一共生活了多少年？（）\nA. 10 年 B. 28 年 C. 5 年 D. 35 年",
    answer: "B",
    explanation: "：鲁滨逊遭遇海难，独自在荒岛生存 28 年后获救。",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-029",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "3. 《骑鹅旅行记》的故事发生在哪个国家？（）\nA. 丹麦 B. 瑞典 C. 挪威 D. 英国",
    answer: "B",
    explanation: "：本书是瑞典女作家塞尔玛・拉格洛夫创作，也是世界唯一获诺贝尔文学奖的童话作品。",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-030",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "4. 小男孩尼尔斯因为捉弄谁，被变成拇指大的小人儿？（）\nA. 燕子 B. 雄鹅 C. 小精灵 D. 大雁阿卡",
    answer: "C",
    explanation: "：尼尔斯调皮欺负家中小精灵，小精灵惩罚他，把他变小。",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-031",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "5. 四本书中，属于纪实历险小说的是（）\nA.《爱丽丝漫游奇境》 B.《鲁滨逊漂流记》 C.《骑鹅旅行记》 D.《汤姆・索亚历险记》",
    answer: "B",
    explanation: "：鲁滨逊故事以真人经历为原型，偏写实；其余三本带有童话、奇幻色彩。",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-032",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "6. 《爱丽丝漫游奇境》作者是（）\nA. 刘易斯・卡罗尔 B. 笛福 C. 马克吐温 D. 塞尔玛",
    answer: "A",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-033",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "7. 《汤姆・索亚历险记》中，汤姆靠什么让小伙伴主动替他刷栅栏？（）\nA. 花钱雇佣 B. 假装刷墙是稀有好玩的事\nC. 逼迫威胁 D. 告诉大人",
    answer: "B",
    explanation: "：经典情节，汤姆聪明狡黠，勾起同伴好奇心，交换礼物换刷墙机会。",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-034",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "8. 《汤姆・索亚历险记》作者马克・吐温是哪国人？（）\nA. 英国 B. 法国 C. 美国 D. 瑞典",
    answer: "C",
    tags: ["阅读理解"],
  },
  {
    id: "g4-q-035",
    grade: 4,
    type: "reading",
    typeLabel: "阅读理解",
    question: "10. 疯帽匠、柴郡猫、红心王后出自哪本书？（）\nA.《鲁滨逊漂流记》 B.《爱丽丝漫游奇境》 C.《骑鹅旅行记》 D.《汤姆・索亚历险记》",
    answer: "B",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-001",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1. 给带横线的字注音：\n春风又绿江南岸（　　）\nA.lǜ    B.lu     C.nu",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-002",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "3. 判断对错\n\"遗民泪尽胡尘里\"中\"遗民\"指遗留下来的百姓。（　　）\n二、文学常识题",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-003",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "5.《长相思》的作者纳兰性德是哪个朝代的词人？（　　）\nA. 宋朝　　B. 元朝　　C. 清朝　　D. 明朝",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-004",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "7.王安石写《泊船瓜洲》时，正处于什么处境？（　　）\nA. 被贬途中　　B. 奉召回京途中　　C. 边疆戍守　　D. 游历山水\n三、理解题",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-005",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "9.《示儿》写于陆游去世前，表达他对国家统一的深切期盼。（　　）",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-006",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "11. 表达陆游希望宋朝军队收复失地的诗句：\n　　王师北定中原日，___________________________。\nA. 但悲不见九州同  B. 家祭无忘告乃翁   C. 死去元知万事空",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-007",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1.　A.lǜ",
    answer: "2. C. 壁立",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-008",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "3.  ✓\n二、文学常识题",
    answer: "4. A.王安石·北宋",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-009",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "5.C清朝",
    answer: "6.A长相思",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-010",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "7.B 奉召回京途中\n三、理解题",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-011",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "11. B.家祭无忘告乃翁",
    answer: "12. B.千磨万击还坚劲",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-012",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "13.　A.对故乡的深切思念",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-001",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1. 梁山伯与祝英台死后化成了___________。\nA. 飞鸟   B. 鱼   C. 蝴蝶",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-002",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "3. 《白蛇传》中，白娘子被法海和尚压在___________下。\nA.白石塔    B. 雷峰塔    C. 千寻塔\n二、判断题（对的打✓，错的打✗）",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-003",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "2. 牛郎织女的故事是民间四大爱情故事之一。（　　）",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-004",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "4. 《猎人海力布》是一个蒙古族民间故事。（　　）",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-005",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1. 下列哪一项不属于中国四大民间故事？（　　）\nA. 牛郎织女　　B. 梁山伯与祝英台　　C. 嫦娥奔月　　D. 孟姜女哭长城",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-006",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "3. 牛郎织女被谁拆散了？（　　）\nA. 牛郎的哥哥　　B. 王母娘娘　　C. 老牛　　D. 织女的父亲",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-007",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1. 《西游记》中，孙悟空是从___________里蹦出来的\nA.石头          B.城墙        C.水里",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-008",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "3. 《红楼梦》中，男主角叫___________，女主角叫___________。\nA. 贾宝玉 林黛玉 B. 贾宝玉 薛宝钗 C. 贾宝玉  王熙凤\n二、判断题（对的打✓，错的打✗）",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-009",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "2. 《三国演义》中，诸葛亮用\"空城计\"对付的是曹操。（　　）",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-010",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "4. 《西游记》一共经历了八十一难才取到真经。（　　）",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-011",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1. \"孙悟空三打白骨精\"这个故事出自哪部名著？（　　）\nA. 《三国演义》　　B. 《西游记》　　C. 《水浒传》　　D. 《红楼梦》",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-012",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "3. 鲁智深倒拔垂杨柳的故事体现了他的什么特点？（　　）\nA. 聪明机智　　B. 力大无穷　　C. 胆小怕事　　D. 阴险狡诈",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-013",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "5. 唐僧师徒去西天取经，\"西天\"指的是今天的哪里？（　　）\nA. 日本　　B. 印度　　C. 新疆　　D. 西藏",
    answer: "五年级上册：民间故事",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-014",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1. C蝴蝶",
    answer: "2. A长城",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-015",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "3. B雷峰塔\n二、判断题",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-016",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1. C（嫦娥奔月属于神话故事，非民间四大故事）",
    answer: "2. C（舍己为人）",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-017",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "3. B（王母娘娘）",
    answer: "4. B（口口相传）",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-018",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1.A石头",
    answer: "2.C武松",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-019",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "3.A贾宝玉　林黛玉\n二、判断题",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g5-q-020",
    grade: 5,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1. B  2. C（林冲是《水浒传》中的）  3. B  4. B  5. B",
    answer: "待补充",
    tags: ["阅读理解"],
  },
  {
    id: "g6-q-001",
    grade: 6,
    type: "pinyin",
    typeLabel: "拼音",
    question: "1. 下列加点字注音完全正确的一项是（  ）\nA. 处（chǔ）理　暂（zhàn）时　拘束（shù）\nB. 的（dí）确　参（cān）加　率（lǜ）领\nC. 提（tí）防　便（biàn）宜　折（zhē）腾\nD. 应（yīng）该　颤（chàn）抖　哄（hōng）堂大笑",
    answer: "B",
    tags: ["拼音"],
  },
  {
    id: "g6-q-002",
    grade: 6,
    type: "pinyin",
    typeLabel: "拼音",
    question: "2.下列词语中，加点字的读音相同的一组是（  ）\nA. 好（hào）学——爱好（hào）运动\nB. 宁（níng）静——宁（nìng）可\nC. 似乎（sì）——似（shì）的\nD. 朝（cháo）气——朝（zhāo）阳",
    answer: "A",
    tags: ["拼音"],
  },
  {
    id: "g6-q-003",
    grade: 6,
    type: "pinyin",
    typeLabel: "拼音",
    question: "3. 下列词语中，读音全部正确的一组是（  ）\nA. 间（jiān）隔　看（kān）守　正（zhèng）月\nB. 喝（hè）彩　供（gòng）应　劲（jìn）头\nC. 省（shěng）得　载（zài）歌载舞　传（zhuàn）记\nD. 哄（hōng）骗　奔（bèn）走　模（mó）范",
    answer: "C",
    tags: ["拼音"],
  },
  {
    id: "g6-q-004",
    grade: 6,
    type: "pinyin",
    typeLabel: "拼音",
    question: "4. 下列各组词语中，加点字的读音完全不同的一组是（  ）\nA. 燃烧（rán）——冉冉（rǎn）升起\nB. 消（xiāo）灭——削（xiāo）苹果\nC. 尽（jìn）力——情不自禁（jìn）\nD. 涨（zhǎng）潮——涨（zhàng）红了脸",
    answer: "D",
    tags: ["拼音"],
  },
  {
    id: "g6-q-005",
    grade: 6,
    type: "pinyin",
    typeLabel: "拼音",
    question: "5.下列\"难\"字的注音和组词，有误的一项是（  ）\nA. nán——困难\nB. nàn——难民\nC. nán——难题\nD. nàn——遇难",
    answer: "B（\"难民\"的\"难\"应读 nán，不读 nàn；\"nàn\"的组词应为\"灾难\"\"遇难\"）",
    tags: ["拼音"],
  },
  {
    id: "g6-q-006",
    grade: 6,
    type: "pinyin",
    typeLabel: "拼音",
    question: "6. 下列词语中，字形和注音完全正确的一项是（  ）\nA. 苍（cāng）茫　弥（mí）漫　颓（tuí）唐\nB. 捐（juān）献　鞭（biān）炮　辽（liáo）阔\nC. 蜿（wān）蜒　婉（wǎn）转　惋（wǎn）惜\nD. 以上三组均正确",
    answer: "D",
    tags: ["拼音"],
  },
  {
    id: "g6-q-007",
    grade: 6,
    type: "pinyin",
    typeLabel: "拼音",
    question: "7. 下列句子中，加点字的读音正确的一项是（  ）\nA. 他的伤口已经结（jié）了痂，结（jiē）实多了。\nB. 他很好（hǎo）学，对学习的好（hào）奇心很强。\nC. 这道题的解（jiě）法很特别，解（jiě）答出来不容易。\nD. 他朝（cháo）着前方奔跑，朝（zhāo）气蓬勃。",
    answer: "D",
    tags: ["拼音"],
  },
  {
    id: "g6-q-008",
    grade: 6,
    type: "pinyin",
    typeLabel: "拼音",
    question: "8. \"弄\"字有两个读音，下列组词正确的一项是（  ）\nA. 弄（lòng）堂——弄（nòng）脏\nB. 弄（nòng）堂——弄（lòng）脏\nC. 弄（nòng）堂——弄（nòng）脏\nD. 弄（lòng）堂——弄（lòng）脏",
    answer: "A（弄堂读 lòng，弄脏读 nòng）",
    tags: ["拼音"],
  },
  {
    id: "g6-q-009",
    grade: 6,
    type: "pinyin",
    typeLabel: "拼音",
    question: "9. 下列词语中，加点字的读音与\"血（xuè）液\"中\"血\"字读音相同的一项是（  ）\nA. 流血（xuè）牺牲\nB. 血（xiě）流不止\nC. 呕心沥血（xuè）\nD. A和C",
    answer: "D",
    tags: ["拼音"],
  },
  {
    id: "g6-q-010",
    grade: 6,
    type: "pinyin",
    typeLabel: "拼音",
    question: "10. 下列带有\"和\"字的词语，读音判断正确的一项是（  ）\nA. 和（hé）平　和（huó）面　和（hè）诗　和（huò）药\nB. 和（hé）平　和（hé）面　和（hé）诗　和（hé）药\nC. 和（hè）平　和（huó）面　和（hé）诗　和（huò）药\nD. 和（hé）平　和（huò）面　和（hè）诗　和（huó）药",
    answer: "A",
    tags: ["拼音"],
  },
  {
    id: "g6-q-011",
    grade: 6,
    type: "character",
    typeLabel: "识字写字",
    question: "1. 下列各组词语，书写全部正确的一组是（  ）\nA. 再接再厉　融为一体　潜移默化\nB. 按步就班　如愿以偿　精疲力竭\nC. 别出新裁　一马当先　惊慌失措\nD. 随声附和　望眼欲穿　委屈求全",
    answer: "A（B\"按步就班\"应为\"按部就班\"；C\"别出新裁\"应为\"别出心裁\"；D\"委屈求全\"应为\"委曲求全\"）",
    tags: ["识字写字"],
  },
  {
    id: "g6-q-012",
    grade: 6,
    type: "character",
    typeLabel: "识字写字",
    question: "2. 下列词语中，没有错别字的一组是（  ）\nA. 蜿蜒　婉转　惋惜　碗筷\nB. 沧桑　仓库　苍白　藏青\nC. 账单　帐篷　涨价　障碍\nD. 嘹亮　了望　眺望　瞭望台",
    answer: "A（B、C、D各有一个字形混淆，A全部正确）",
    explanation: "注：D中\"了望\"应为\"瞭望\"，\"瞭望台\"正确——实际D有误。A全正确。",
    tags: ["识字写字"],
  },
  {
    id: "g6-q-013",
    grade: 6,
    type: "character",
    typeLabel: "识字写字",
    question: "3.下列各组词语中，有错别字的一组是（  ）\nA. 精忠报国　不屈不挠　坚贞不渝\nB. 气势磅礴　波澜壮阔　震耳欲聋\nC. 见微知著　不可思意　出类拔萃\nD. 脍炙人口　耳熟能详　博览群书",
    answer: "C（\"不可思意\"应为\"不可思议\"）",
    tags: ["识字写字"],
  },
  {
    id: "g6-q-014",
    grade: 6,
    type: "character",
    typeLabel: "识字写字",
    question: "4. 下列句子中，没有错别字的一句是（  ）\nA. 他做事粗心大意，经常出差错，老师对他进行了批评教育。\nB. 同学们在操场上生龙活虎地做着各种游戏，喜笑颜开。\nC. 我们要爱护环境，节约用水，不能铺张浪废。\nD. 运动会上，大家奋勇争先，整个运动场沸沸腾腾。",
    answer: "B（A“出差错”应为“出岔错”；C\"铺张浪废\"应为\"铺张浪费\"；D\"沸沸腾腾\"应为\"热气腾腾\"或\"沸沸扬扬\"不适用此处）",
    tags: ["识字写字"],
  },
  {
    id: "g6-q-015",
    grade: 6,
    type: "character",
    typeLabel: "识字写字",
    question: "5.下列加点字的笔画数，判断正确的一项是（  ）\nA. \"鼎\"字共12画\nB. \"赢\"字共15画\nC. \"爨\"字共28画\nD. \"鬱\"（郁的繁体）字共16画",
    answer: "A（赢17画，爨30画，A正确）",
    tags: ["识字写字"],
  },
  {
    id: "g6-q-016",
    grade: 6,
    type: "character",
    typeLabel: "识字写字",
    question: "6.下列形近字，字义解释匹配正确的一项是（  ）\nA. 侯（等待）——候（王侯）\nB. 辩（分辨）——辨（争辩）\nC. 燥（急躁）——躁（干燥）\nD. 戊（第五天干）——戌（第十一地支）——戍（守卫）",
    answer: "D",
    tags: ["识字写字"],
  },
  {
    id: "g6-q-017",
    grade: 6,
    type: "character",
    typeLabel: "识字写字",
    question: "7. 下列词语中，加点字意思相同的一组是（  ）\nA. 不以为然——理所当然——突然\nB. 意味深长——长篇大论——长城\nC. 精益求精——精疲力竭——精打细算\nD. 心旷神怡——怡然自得——怡情悦性",
    answer: "D（三个\"怡\"均表示\"愉快、安适\"）",
    tags: ["识字写字"],
  },
  {
    id: "g6-q-018",
    grade: 6,
    type: "character",
    typeLabel: "识字写字",
    question: "8. 根据偏旁推断字义，下列判断有误的一项是（  ）\nA. \"溺\"含\"氵\"，与水有关——溺水\nB. \"悟\"含\"忄\"，与心理有关——领悟\nC. \"搏\"含\"扌\"，与手的动作有关——搏斗\nD. \"暮\"含\"木\"，与树木有关——暮色",
    answer: "D（\"暮\"的部首是\"日\"，不是\"木\"，表示傍晚、日将落）",
    tags: ["识字写字"],
  },
  {
    id: "g6-q-019",
    grade: 6,
    type: "character",
    typeLabel: "识字写字",
    question: "9. 下列词语中，加点字的书写与用法完全正确的一项是（  ）\nA. 历行节约（厉）　墨守陈规（成）　一愁莫展（筹）\nB. 厉行节约　墨守成规　一筹莫展\nC. 厉行节约　墨守陈规　一筹莫展\nD. 历行节约　墨守成规　一愁莫展",
    answer: "B",
    tags: ["识字写字"],
  },
  {
    id: "g6-q-020",
    grade: 6,
    type: "character",
    typeLabel: "识字写字",
    question: "10. 下列各组词语中，每字都能与\"心\"字组成词语的一组是（  ）\nA. 开、细、用、放\nB. 真、全、核、精\nC. 放、专、粗、耐\nD. A和C",
    answer: "D（开心、细心、用心、放心；放心、专心、粗心、耐心——均可成词）",
    tags: ["识字写字"],
  },
  {
    id: "g6-q-021",
    grade: 6,
    type: "word",
    typeLabel: "词语理解",
    question: "1.下列成语使用正确的一项是（  ）\nA. 同学们在课间玩耍，个个生龙活虎，精神焕发。\nB. 他对这次考试的失败耿耿于怀，整天沾沾自喜。\nC. 节日广场上，人们人声鼎沸，大家在争论政策得失。\nD. 这本书我读了三番五次，每次都有新的收获，真是津津有味。",
    answer: "A（B矛盾；C\"人声鼎沸\"形容声音嘈杂，而非争论；D\"三番五次\"指一次又一次，与\"每次都有新收获\"语义不矛盾，但\"三番五次\"通常含有\"反复\"的贬义语境，A最为准确）",
    tags: ["词语理解"],
  },
  {
    id: "g6-q-022",
    grade: 6,
    type: "word",
    typeLabel: "词语理解",
    question: "2. 下列词语中，不属于近义词的一组是（  ）\nA. 宽阔——辽阔\nB. 赞扬——称赞\nC. 寂静——喧嚣\nD. 犹豫——踌躇",
    answer: "C（寂静与喧嚣是反义词）",
    tags: ["词语理解"],
  },
  {
    id: "g6-q-023",
    grade: 6,
    type: "word",
    typeLabel: "词语理解",
    question: "3. 下列句子中，加点词语意义解释正确的一项是（  ）\nA. 他神采奕奕——形容无精打采的样子\nB. 她眉开眼笑——形容十分高兴的样子\nC. 大家漠然置之——形容非常重视的样子\nD. 他振振有词——形容无话可说的样子",
    answer: "B",
    tags: ["词语理解"],
  },
  {
    id: "g6-q-024",
    grade: 6,
    type: "word",
    typeLabel: "词语理解",
    question: "4.下列各组词语中，互为反义词的一组是（  ）\nA. 慷慨——吝啬\nB. 勤奋——刻苦\nC. 善良——慈祥\nD. 诚实——真诚",
    answer: "A",
    tags: ["词语理解"],
  },
  {
    id: "g6-q-025",
    grade: 6,
    type: "word",
    typeLabel: "词语理解",
    question: "5. 下列词语中，\"一\"字含义与其他三项不同的一项是（  ）\nA. 一字一句（数量）\nB. 一模一样（加强语气，表示完全）\nC. 一清二楚（加强语气）\nD. 一望无际（加强语气）",
    answer: "A（A中\"一\"表示数量\"一个\"，其余均是加强语气的副词用法）",
    tags: ["词语理解"],
  },
  {
    id: "g6-q-026",
    grade: 6,
    type: "word",
    typeLabel: "词语理解",
    question: "6. 根据语境，下列填入括号内的词语最恰当的一项是（  ）\n无论遇到多大的（  ），他都能保持乐观的心态，从不轻言放弃。\nA. 困境　B. 困难　C. 挫折　D. 困苦",
    answer: "C（\"挫折\"与\"乐观心态\"和\"不轻言放弃\"搭配最自然，也最符合语境）",
    tags: ["词语理解"],
  },
  {
    id: "g6-q-027",
    grade: 6,
    type: "word",
    typeLabel: "词语理解",
    question: "7.下列成语中，出自历史故事的一组是（  ）\nA. 卧薪尝胆　破釜沉舟　草木皆兵\nB. 守株待兔　狐假虎威　刻舟求剑\nC. 一鸣惊人　叶公好龙　亡羊补牢\nD. A、B、C都是出自历史故事或寓言故事",
    answer: "D（A出自历史；B出自寓言；C出自历史典故和寓言）",
    tags: ["词语理解"],
  },
  {
    id: "g6-q-028",
    grade: 6,
    type: "word",
    typeLabel: "词语理解",
    question: "8.下列词语中，感情色彩判断正确的一项是（  ）\nA. \"鼓励\"是贬义词\nB. \"阴谋\"是褒义词\nC. \"勇敢\"是褒义词\nD. \"虚伪\"是中性词",
    answer: "C",
    tags: ["词语理解"],
  },
  {
    id: "g6-q-029",
    grade: 6,
    type: "word",
    typeLabel: "词语理解",
    question: "9. 下列句子中，加点的词使用不恰当的一项是（  ）\nA. 爸爸精益求精，反复修改报告，直到满意为止。\nB. 春天来了，万物复苏，大地充满了生机。\nC. 他一马当先，率先冲过了终点线。\nD. 这件事情已经无可厚非，我们应该重新考虑。",
    answer: "D（\"无可厚非\"指没有太大的错误，不应受到责备，不能用来表示\"应该重新考虑\"，语义矛盾）",
    tags: ["词语理解"],
  },
  {
    id: "g6-q-030",
    grade: 6,
    type: "word",
    typeLabel: "词语理解",
    question: "10. 下列句子中，加点词语与括号内的解释不匹配的一项是（  ）\nA. 父亲佝偻着背走在前方。（身体弯曲）✓\nB. 他踌躇半天，才开口说话。（犹豫不决）✓\nC. 夕阳西沉，天边出现了美丽的晚霞。（向西下沉）✓\nD. 他说话振振有词，其实心虚得很。（理直气壮，说话有力）✗",
    answer: "D（\"振振有词\"指理由似乎很充分地说话，多含贬义，指强词夺理，不是真正的理直气壮）",
    tags: ["词语理解"],
  },
  {
    id: "g6-q-031",
    grade: 6,
    type: "sentence",
    typeLabel: "句子练习",
    question: "1. 下列句子中，修辞手法判断正确的一项是（  ）\nA. \"弯弯的月亮像一只小船\"——拟人\nB. \"春天是个害羞的小姑娘\"——比喻\nC. \"难道我们不应该爱护环境吗？\"——设问\nD. \"桃树、杏树、梨树，你不让我，我不让你，都开满了花赶趟儿\"——夸张",
    answer: "B（A是比喻；C是反问；D是拟人；B是比喻，正确）",
    tags: ["句子练习"],
  },
  {
    id: "g6-q-032",
    grade: 6,
    type: "sentence",
    typeLabel: "句子练习",
    question: "2.下列句子中，标点符号使用完全正确的一项是（  ）\nA. 他问我：\"你明天去图书馆吗？\"\nB. 妈妈买了苹果、梨、香蕉、和葡萄。\nC. \"你要好好学习，\"他说，\"将来才能有出息\"。\nD. 这道题有三种解法：加法、减法和乘法、除法。",
    answer: "A（B顿号与\"和\"重复；C句号应在引号内；D顿号用法混乱）",
    tags: ["句子练习"],
  },
  {
    id: "g6-q-033",
    grade: 6,
    type: "sentence",
    typeLabel: "句子练习",
    question: "3. 下列病句，修改方法正确的一项是（  ）\n原句：经过老师的耐心辅导，使我终于明白了这道题的解法。\nA. 删去\"经过\"\nB. 删去\"使\"\nC. 删去\"经过……辅导，\"\nD. A或B均可",
    answer: "D（删去\"经过\"则\"老师的耐心辅导使我……\"，正确；删去\"使\"则\"经过老师的耐心辅导，我终于……\"，也正确）",
    tags: ["句子练习"],
  },
  {
    id: "g6-q-034",
    grade: 6,
    type: "sentence",
    typeLabel: "句子练习",
    question: "4. 下列句子中，表达方式判断正确的一项是（  ）\nA. \"春天来了，小草悄悄钻出地面\"——议论\nB. \"他是一个勇敢、善良的孩子\"——描写\nC. \"远处的山峦连绵起伏，像一条巨龙蜿蜒盘旋\"——描写\nD. \"我认为，我们应该爱护大自然\"——叙述",
    answer: "C",
    tags: ["句子练习"],
  },
  {
    id: "g6-q-035",
    grade: 6,
    type: "sentence",
    typeLabel: "句子练习",
    question: "5.下列各句中，用了\"把字句\"的一项是（  ）\nA. 这本书被他看完了。\nB. 他把这本书看完了。\nC. 这本书他已经看完了。\nD. 他这本书借走了没有？",
    answer: "B",
    tags: ["句子练习"],
  },
  {
    id: "g6-q-036",
    grade: 6,
    type: "sentence",
    typeLabel: "句子练习",
    question: "6. 下列各句中，关联词语使用正确的一项是（  ）\nA. 虽然天气很冷，但是他坚持锻炼。\nB. 因为只要努力，所以就能成功。\nC. 不管风多大，所以他还是出发了。\nD. 既然他已经知道了，但是还要再告诉他一遍。",
    answer: "A",
    tags: ["句子练习"],
  },
  {
    id: "g6-q-037",
    grade: 6,
    type: "sentence",
    typeLabel: "句子练习",
    question: "7. 对下列句子的缩句，正确的一项是（  ）\n原句：金黄色的树叶在秋风中缓缓飘落下来。\nA. 树叶飘落。\nB. 金黄色的树叶飘落。\nC. 树叶在秋风中飘落。\nD. 叶子飘落下来。",
    answer: "A（缩句去掉所有修饰成分，只保留主谓宾核心）",
    tags: ["句子练习"],
  },
  {
    id: "g6-q-038",
    grade: 6,
    type: "sentence",
    typeLabel: "句子练习",
    question: "8. 下列句子中，语气最强烈的反问句是（  ）\nA. 他这样做是不对的吗？\nB. 难道他这样做是对的吗？\nC. 他这样做怎么可能是对的？\nD. 他这样做对吗？",
    answer: "B（\"难道……吗\"是最典型、语气最强的反问句式）",
    tags: ["句子练习"],
  },
  {
    id: "g6-q-039",
    grade: 6,
    type: "sentence",
    typeLabel: "句子练习",
    question: "9.下列句子中，使用了夸张修辞手法的一项是（  ）\nA. 她的笑容像阳光一样温暖。\nB. 他跑得飞快，像一阵风。\nC. 这块石头重得能压死一头牛。\nD. 蚂蚁在努力地搬运食物。",
    answer: "C（夸张手法，极言其重）",
    tags: ["句子练习"],
  },
  {
    id: "g6-q-040",
    grade: 6,
    type: "sentence",
    typeLabel: "句子练习",
    question: "10. 对下列句子的判断，正确的一项是（  ）\n①\"书是人类进步的阶梯。\"（比喻）\n②\"桃花潭水深千尺，不及汪伦送我情。\"（夸张+对比）\n③\"飞流直下三千尺，疑是银河落九天。\"（夸张）\n④\"春眠不觉晓，处处闻啼鸟。\"（拟人）\nA. ①②③正确，④错误\nB. ①③正确，②④错误\nC. ①②③④全部正确\nD. ①②③正确，④中\"闻啼鸟\"是写实描写，非拟人",
    answer: "D（④中没有拟人手法，只是客观描写春天听到鸟叫声）",
    tags: ["句子练习"],
  },
  {
    id: "g6-q-041",
    grade: 6,
    type: "reading",
    typeLabel: "阅读理解",
    question: "1. 文段中，描写父亲外貌的句子是（  ）\nA. \"提着我沉甸甸的行李，走得气喘吁吁\"\nB. \"穿着一件洗得发白的旧棉袄\"\nC. \"掏出手帕擦了擦额头的汗\"\nD. \"笑着说：孩子，要好好学习\"",
    answer: "B（B是外貌描写；A是动作描写；C是动作描写；D是语言描写）",
    tags: ["阅读理解"],
  },
  {
    id: "g6-q-042",
    grade: 6,
    type: "reading",
    typeLabel: "阅读理解",
    question: "2. \"我看见他转身离去的背影，心里酸酸的\"，这里的\"酸酸的\"最能表达（  ）\nA. 我对父亲离去感到高兴\nB. 我对父亲深沉的爱和依依不舍的感情\nC. 我对上学感到害怕\nD. 我觉得父亲不爱我",
    answer: "B",
    tags: ["阅读理解"],
  },
  {
    id: "g6-q-043",
    grade: 6,
    type: "reading",
    typeLabel: "阅读理解",
    question: "3. 文段中，最能体现父亲深沉父爱的细节描写是（  ）\nA. \"笑着说：孩子，要好好学习\"\nB. \"掏出手帕擦了擦额头的汗\"\nC. \"穿着一件洗得发白的旧棉袄，提着行李，走得气喘吁吁\"\nD. A和C",
    answer: "D（A是语言中饱含牵挂；C是动作体现辛劳；二者共同体现父爱）",
    tags: ["阅读理解"],
  },
  {
    id: "g6-q-044",
    grade: 6,
    type: "reading",
    typeLabel: "阅读理解",
    question: "4. \"那件旧棉袄的背影，从此刻在了我心里\"，这句话的意思是（  ）\nA. 父亲的棉袄很漂亮，令我印象深刻\nB. 父亲送我上学的情景和背影永远留在我心中\nC. 我很舍不得那件棉袄\nD. 父亲的背影很奇特",
    answer: "B",
    tags: ["阅读理解"],
  },
  {
    id: "g6-q-045",
    grade: 6,
    type: "reading",
    typeLabel: "阅读理解",
    question: "5.下列对文段写作手法的分析，正确的一项是（  ）\nA. 本文以抒情为主，几乎没有叙事\nB. 本文综合运用了外貌、动作、语言、心理描写\nC. 本文只用了比喻和拟人的修辞手法\nD. 本文没有任何情感表达",
    answer: "B",
    tags: ["阅读理解"],
  },
  {
    id: "g6-q-046",
    grade: 6,
    type: "reading",
    typeLabel: "阅读理解",
    question: "6. 本文段的中心论点是（  ）\nA. 爬山可以增强体质\nB. 读书要越多越好\nC. 读书的深度决定人生的高度\nD. 喜欢爬山的人才能读好书",
    answer: "C",
    tags: ["阅读理解"],
  },
  {
    id: "g6-q-047",
    grade: 6,
    type: "reading",
    typeLabel: "阅读理解",
    question: "7. \"有人如饥似渴、博览群书\"中，\"如饥似渴\"的意思是（  ）\nA. 非常饥饿和口渴\nB. 形容迫切地希望得到知识，学习非常勤奋积极\nC. 对食物有强烈的需求\nD. 比喻一个人脾气暴躁",
    answer: "B",
    tags: ["阅读理解"],
  },
  {
    id: "g6-q-048",
    grade: 6,
    type: "reading",
    typeLabel: "阅读理解",
    question: "8. \"浅尝辄止\"的反义词，最恰当的一项是（  ）\nA. 囫囵吞枣　B. 精益求精　C. 深入钻研　D. 一知半解",
    answer: "C",
    tags: ["阅读理解"],
  },
  {
    id: "g6-q-049",
    grade: 6,
    type: "reading",
    typeLabel: "阅读理解",
    question: "9. 文段中，\"有人爱登顶\"和\"有人只在山脚流连\"分别比喻什么？（  ）\nA. 喜欢爬山的人和不喜欢爬山的人\nB. 读书深入、博览群书的人和浅尝辄止的人\nC. 学习好的人和学习差的人\nD. 爱读书的人和不爱读书的人",
    answer: "B",
    tags: ["阅读理解"],
  },
  {
    id: "g6-q-050",
    grade: 6,
    type: "reading",
    typeLabel: "阅读理解",
    question: "10. 下列对本文写法的判断，正确的一项是（  ）\nA. 本文用了\"爬山\"作类比，说明读书的道理，运用了类比论证\nB. 本文没有使用任何修辞手法\nC. 本文是记叙文，记叙了作者爬山的经历\nD. 本文表达的观点是爬山比读书更重要",
    answer: "A",
    tags: ["阅读理解"],
  },
  {
    id: "g6-q-051",
    grade: 6,
    type: "writing",
    typeLabel: "写作练习",
    question: "1.写作文时，\"审题\"最重要。下列对作文题目《那一次，我真的很感动》审题正确的是（  ）\nA. 可以写很多次感动的经历，数量不限\nB. 重点在\"那一次\"，要写一次具体的事，核心情感是\"感动\"\nC. 只能写别人感动了我，不能写我感动了别人\nD. 题目没有限定时间，所以写什么时候的事都可以",
    answer: "B",
    tags: ["写作练习"],
  },
  {
    id: "g6-q-052",
    grade: 6,
    type: "writing",
    typeLabel: "写作练习",
    question: "2. 下列各篇作文开头方式中，最能吸引读者的一项是（  ）\nA. 今天，我要写一篇关于妈妈的作文。\nB. 从我记事起，妈妈就一直陪伴着我。\nC. 那个深夜，电话铃声突然响起，妈妈握着话筒的手微微颤抖……\nD. 妈妈今年四十岁，是一名普通的工人。",
    answer: "C（设置悬念，制造紧张感，最能吸引读者）",
    tags: ["写作练习"],
  },
  {
    id: "g6-q-053",
    grade: 6,
    type: "writing",
    typeLabel: "写作练习",
    question: "3. 描写人物时，下列哪种方法最能体现人物的性格特点？（  ）\nA. 只写人物的外貌\nB. 只写人物的年龄和职业\nC. 综合运用外貌、动作、语言、心理、神态描写\nD. 只写别人对这个人的评价",
    answer: "C",
    tags: ["写作练习"],
  },
  {
    id: "g6-q-054",
    grade: 6,
    type: "writing",
    typeLabel: "写作练习",
    question: "4. 写作文时，选材应注意（  ）\nA. 选越长的故事越好，越能体现写作水平\nB. 选自己亲身经历的、有真情实感的事\nC. 选听说过的名人事迹，显得有文化\nD. 越奇特越好，越不常见越能吸引人",
    answer: "B",
    tags: ["写作练习"],
  },
  {
    id: "g6-q-055",
    grade: 6,
    type: "writing",
    typeLabel: "写作练习",
    question: "5. 下列关于作文结尾的说法，正确的一项是（  ）\nA. 结尾越短越好，一句话结束最佳\nB. 结尾要首尾呼应，或点明中心，或留有余韵\nC. 结尾必须用一句名言警句\nD. 结尾只需要简单总结开头说过的内容",
    answer: "B",
    tags: ["写作练习"],
  },
  {
    id: "g6-q-056",
    grade: 6,
    type: "writing",
    typeLabel: "写作练习",
    question: "6.写《我的同学》这篇作文，下列立意最好的一项是（  ）\nA. 描写同学的外貌，说明他（她）长得很好看\nB. 通过两三件典型事例，展现同学独特的性格和品质\nC. 列举同学的优点和缺点，进行全面评价\nD. 写同学的家庭情况和父母的职业",
    answer: "B",
    tags: ["写作练习"],
  },
  {
    id: "g6-q-057",
    grade: 6,
    type: "writing",
    typeLabel: "写作练习",
    question: "7. 下列关于写景作文的技巧，说法正确的一项是（  ）\nA. 写景只需要用比喻，其他修辞不重要\nB. 写景时要按照一定顺序（时间、空间、观察角度），做到层次清晰\nC. 写景作文不需要有感情，只需如实描写\nD. 写景越详细越好，每一棵草、每一块石头都要写到",
    answer: "B",
    tags: ["写作练习"],
  },
  {
    id: "g6-q-058",
    grade: 6,
    type: "writing",
    typeLabel: "写作练习",
    question: "8.写《一件难忘的事》，以下哪个细节描写最能体现\"难忘\"？（  ）\nA. 事情发生的具体日期\nB. 事情发生时，人物内心的感受和情绪变化\nC. 事情发生的地点\nD. 参与事件的人数",
    answer: "B",
    tags: ["写作练习"],
  },
  {
    id: "g6-q-059",
    grade: 6,
    type: "writing",
    typeLabel: "写作练习",
    question: "9. 下列各句中，最适合作为一篇写人作文的\"点题句\"（揭示中心思想的句子）的是（  ）\nA. 他今年十二岁，是我的好朋友。\nB. 就是这样一个普通而又坚强的人，用行动诠释了什么叫作\"不放弃\"。\nC. 他喜欢打篮球和看书。\nD. 他的妈妈是一名老师，爸爸是一名医生。",
    answer: "B",
    tags: ["写作练习"],
  },
  {
    id: "g6-q-060",
    grade: 6,
    type: "writing",
    typeLabel: "写作练习",
    question: "10. 写一篇以\"感恩\"为主题的作文，下列选材最恰当的一项是（  ）\nA. 写一次自己考试得了满分的经历\nB. 写一次在老师耐心帮助下，自己走出困境、深受感动的经历\nC. 写自己买了一件漂亮衣服的开心故事\nD. 写一次旅游中看到了美丽风景的见闻",
    answer: "B（最契合\"感恩\"主题，有具体的感恩对象和情感表达）",
    tags: ["写作练习"],
  },
];
